name: Conferencia Automatica Lotofacil

on:
  schedule:
    - cron: "15 1 * * *" # 22:15 Horário de Brasília
  workflow_dispatch:

jobs:
  conferir-resultados:
    runs-on: ubuntu-latest

    env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_KEY }}
        SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_KEY }}
    
    steps:
      - name: Checkout do repositorio
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: 'pip'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install pandas supabase python-dotenv requests fastapi

      - name: Localizar e Executar Script
        env:
          PYTHONPATH: .
        run: |
          python scripts/conferir_resultados.py
